import { useState, useCallback } from 'react';
import type { Session } from '../lib/types';

interface SessionCardProps {
  session: Session;
  isActive: boolean;
  onSelect: (sessionId: string) => void;
  onClose: (sessionId: string) => void;
}

export function SessionCard({ session, isActive, onSelect, onClose }: SessionCardProps) {
  const [confirmDelete, setConfirmDelete] = useState(false);

  const badgeStyle: React.CSSProperties =
    session.status === 'run'
      ? { background: 'rgba(0,255,135,0.15)', color: '#f97316' }
      : { background: 'rgba(100,100,100,0.2)', color: '#666' };

  const handleDeleteClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    setConfirmDelete(true);
  }, []);

  const handleConfirmDelete = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    onClose(session.id);
    setConfirmDelete(false);
  }, [onClose, session.id]);

  const handleCancelDelete = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    setConfirmDelete(false);
  }, []);

  return (
    <button
      type="button"
      onClick={() => onSelect(session.id)}
      className="relative w-full text-left"
      style={{
        aspectRatio: '1 / 1.18',
        background: isActive
          ? 'linear-gradient(135deg, rgba(0,255,135,0.05), #111111)'
          : '#111111',
        borderRadius: 10,
        border: isActive ? '1px solid #f97316' : '1px solid #222222',
        boxShadow: isActive ? '0 0 0 1px #f97316' : 'none',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Header with traffic lights */}
      <div
        className="flex items-center gap-1.5 px-2.5"
        style={{ height: 24, flexShrink: 0 }}
      >
        <span
          style={{
            width: 8,
            height: 8,
            borderRadius: '50%',
            background: '#ff5f57',
          }}
        />
        <span
          style={{
            width: 8,
            height: 8,
            borderRadius: '50%',
            background: '#ffbd2e',
          }}
        />
        <span
          style={{
            width: 8,
            height: 8,
            borderRadius: '50%',
            background: '#28c840',
          }}
        />
        <span
          className="ml-1 truncate"
          style={{
            fontSize: 10,
            color: '#666',
            fontFamily: 'JetBrains Mono, monospace',
            flex: 1,
          }}
        >
          {session.name}
        </span>
        {session.status === 'run' && (
          <span
            className="flex-shrink-0 rounded px-1"
            style={{
              fontSize: 9,
              fontFamily: 'JetBrains Mono, monospace',
              fontWeight: 600,
              letterSpacing: '0.05em',
              ...badgeStyle,
            }}
          >
            RUN
          </span>
        )}
      </div>

      {/* Preview body */}
      <div
        className="relative flex-1 overflow-hidden px-2.5 pt-1"
        style={{ minHeight: 0, background: '#060606' }}
      >
        <pre
          // snapshot is HTML generated by captureColoredScreen (trusted, origin-local)
          dangerouslySetInnerHTML={{
            __html: session.snapshot || '<span style="color:#555">$ _</span>',
          }}
          style={{
            fontSize: 8,
            lineHeight: 1.4,
            fontFamily: 'JetBrains Mono, monospace',
            color: '#d0d0d0',
            whiteSpace: 'pre',
            margin: 0,
            overflow: 'hidden',
          }}
        />

        {/* Bottom fade gradient */}
        <div
          className="pointer-events-none absolute inset-x-0 bottom-0"
          style={{
            height: 20,
            background: isActive
              ? 'linear-gradient(transparent, rgba(17,17,17,0.95))'
              : 'linear-gradient(transparent, #111111)',
          }}
        />
      </div>

      {/* Delete button (red X) */}
      <div
        onClick={handleDeleteClick}
        className="absolute flex items-center justify-center"
        style={{
          bottom: 6,
          right: 6,
          width: 16,
          height: 16,
          background: 'rgba(255,95,87,0.15)',
          border: '1px solid #ff5f57',
          borderRadius: 3,
          fontSize: 10,
          color: '#ff5f57',
          lineHeight: 1,
          cursor: 'pointer',
        }}
      >
        &#x2715;
      </div>

      {/* Delete confirmation overlay */}
      {confirmDelete && (
        <div
          onClick={(e) => e.stopPropagation()}
          className="absolute inset-0 flex flex-col items-center justify-center"
          style={{
            background: 'rgba(6,6,6,0.92)',
            borderRadius: 10,
            zIndex: 10,
          }}
        >
          <span
            style={{
              fontSize: 11,
              color: '#aaa',
              fontFamily: 'JetBrains Mono, monospace',
              marginBottom: 8,
              textAlign: 'center',
              padding: '0 12px',
            }}
          >
            Close <span style={{ color: '#f97316' }}>{session.name}</span>?
          </span>
          <div className="flex gap-3">
            <button
              type="button"
              onClick={handleConfirmDelete}
              style={{
                background: 'rgba(255,95,87,0.2)',
                border: '1px solid #ff5f57',
                borderRadius: 4,
                color: '#ff5f57',
                fontSize: 11,
                fontFamily: 'JetBrains Mono, monospace',
                padding: '4px 14px',
                cursor: 'pointer',
              }}
            >
              Close
            </button>
            <button
              type="button"
              onClick={handleCancelDelete}
              style={{
                background: '#1a1a1a',
                border: '1px solid #333',
                borderRadius: 4,
                color: '#666',
                fontSize: 11,
                fontFamily: 'JetBrains Mono, monospace',
                padding: '4px 14px',
                cursor: 'pointer',
              }}
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </button>
  );
}
